### PR TITLE
Implementation with closure (of course name will be changed if needed)

### PR DESCRIPTION
**Pull request by gburanov**
Another implementation on memory saving - using closure. 
Takes only a little bit more memory (for closures) but increases readability

How will the code looks like
```
	log.SmartSend(cue.INFO, func() (string, cue.Fields) {
		return "smessage", cue.Fields{
			"topic":   topic,
			"message": string(buf),
		}
	})
```

IMHO this one is nicer (but a little bit too many brackets for go =)

PS: It is probably faster as well because we check level only once

### CODE REVIEW

**Comment by itszootime** [comment]
The level check is already done in `send` on the logger. How would you feel about adding a `WithFieldsFunc` method, which is then evaluated by `Context#Fields()`? The changes are a bit bigger, but I think it keeps the interface consistent.

**Comment by itszootime** [comment]
Also, I much prefer this solution over the `EnabledFor` approach

**Comment by gburanov** [comment]
@dynamix  prefers another option =)

I personally think that the other solution is 1) uglier 2) a little bit slower (2 checks) but has less memory consumption (you don't create extra closure all the time)

Also, it will look like this (also not SO elegant =))
```
	log.WithFieldsFunc( func() cue.Fields {
		return cue.Fields{
			"topic":   topic,
			"message": string(buf),
		}
	}).Debug("smessage")
```

**Comment by gburanov** [comment]
Memory usage is 15117 (compared to 14300 here) https://github.com/remerge/cue/pull/2

**Comment by gburanov** [comment]
I realized that we clone the logging, and I removed this clonning.

This means we cannot. call 
log.WithValues(Fields{...}) without smth after it (it will ad a state) - but we were not doing it anyway

Now it is almost as memory efficient like the first solution.

**Comment by gburanov** [comment]
yes, but this will give problems with concurrency...

**Pull request closed without merging**
